export const recentArticleCardClasses = [
	"lg:w-40",
	"md:w-60",
	"flex-auto",
	"lg:h-64",
	"p-2",
	"bg-canvas",
	"overflow-hidden",
	"transition",
	"rounded",
	"border",
	"hover:brightness-95",
	"dark:hover:brightness-125",
	"active:brightness-105",
	"dark:active:brightness-90",
].join(" ");
